import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
const require = createRequire(process.env.INSPIRATION_PLAYWRIGHT + '/package.json');
const { chromium } = require('playwright');
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({viewport:{width:1440,height:1000}});
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto('http://127.0.0.1:5173');
await page.locator('.hero h1').waitFor();
await mkdir('preview', {recursive:true});
await page.screenshot({path:'preview/home.png'});
await page.locator('.hero-cta').click();
await page.locator('#library').scrollIntoViewIfNeeded();
await page.screenshot({path:'preview/library.png'});
if(await page.locator('.card').count() !== 37) throw new Error('素材数量错误');
await page.getByRole('searchbox').fill('不存在的灵感XYZ');
if(await page.locator('.card').count() !== 0) throw new Error('搜索失败');
await page.getByRole('button',{name:'↺ 重置筛选'}).click();
await page.getByRole('button',{name:'Pinterest',exact:true}).click();
const pinCount = await page.locator('.card').count();
if(pinCount === 0 || pinCount === 37) throw new Error('来源筛选失败');
await page.getByRole('button',{name:'↺ 重置筛选'}).click();
await page.locator('.image-button').first().click();
await page.locator('#detail-save').click();
await page.locator('#comment-input').fill('测试评论：自然光与植物层次很有启发。');
await page.getByRole('button',{name:'发布评论'}).click();
if(await page.locator('.comment').count() !== 1) throw new Error('评论发布失败');
await page.screenshot({path:'preview/detail.png'});
await page.keyboard.press('Escape');
await page.reload();
await page.locator('.image-button').first().click();
if(await page.locator('.comment').count() !== 1) throw new Error('评论未保存');
if(await page.locator('#detail-save').getAttribute('aria-pressed') !== 'true') throw new Error('收藏未保存');
await page.keyboard.press('Escape');
for(const width of [1920,1440,1024]) {await page.setViewportSize({width,height:1000}); await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))); if(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw new Error('页面横向溢出');}
const imageFailures = await page.locator('.gallery img').evaluateAll(images => images.filter(i => i.complete && i.naturalWidth === 0).length);
if(imageFailures || errors.length) throw new Error(JSON.stringify({imageFailures,errors}));
await page.evaluate(() => localStorage.clear());
await browser.close();
console.log('通过：37 张素材、搜索、来源筛选、详情开关、收藏与评论持久化、PC 宽度检查，无运行时错误。');

